### PR TITLE
Add `-ndk` to tagPrefix in push script

### PR DESCRIPTION
**Pull request by tafilz**
The ndk images were not pushed by the script.

### CODE REVIEW

**Comment by tafilz** [comment]
@Ghostbird can you take a look on this? Never did array stuff in bash before

**Comment by Ghostbird** [comment]
How stupid of me to forget those. I'll look into it after lunch.

**Comment by Ghostbird** [comment]
Yeah, it generates exactly the right commands. I didn't know this bash array trick either.

**Comment by Ghostbird** [comment]
As far as I can see, yes.

**Review by Ghostbird — APPROVED** [review]

**Pull request merged**
